version: "3.8"

services:
  db_test:
    image: postgres:15
    container_name: fitnesstracker_test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitnesstracker_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_test_data:
